const fileInput = document.querySelector('#instruction-file');
const loadSampleButton = document.querySelector('#load-instruction-sample');
const printButton = document.querySelector('#print-instructions');
const downloadBomButton = document.querySelector('#download-bom');
const subtitle = document.querySelector('#instruction-subtitle');
const summary = document.querySelector('#instruction-summary');
const stepsEl = document.querySelector('#steps');
const message = document.querySelector('#instruction-message');
const PLATE_WORLD_HEIGHT = 0.4;
const CATEGORY_COLORS = { brick: '#d8c7a4', roof_tile: '#b9564b', ridge_tile: '#e5a15f' };
const PREVIOUS_TOP = '#d7dce4', PREVIOUS_SIDE_A = '#bcc4d0', PREVIOUS_SIDE_B = '#aeb8c6';
let currentBundle = null;
function validateBundle(bundle){if(!bundle?.brick_model?.parts||!bundle?.bom?.lines)throw new Error('Export BrickHouse invalide.');if(!bundle.assembly_plan?.steps?.length)throw new Error('Cet export ne contient pas encore d’AssemblyPlan.');if(bundle.assembly_plan.total_parts!==bundle.brick_model.parts.length)throw new Error('AssemblyPlan incomplet.');}
function partMap(bundle){return new Map(bundle.brick_model.parts.map(p=>[p.placement_id,p]));}
function rawDimensions(part){const m=part.part_id.match(/_(\d+)X(\d+)$/);return m?{a:+m[1],b:+m[2]}:{a:1,b:1};}
function parseDimensions(part){const {a,b}=rawDimensions(part);let width=a,length=b;if(part.rotation_quarter_turns%2===1)[width,length]=[length,width];return{width,length,height:part.category==='ridge_tile'?.4:1.2};}
function aggregateStepParts(step,byPlacement){const counts=new Map();for(const id of step.placement_ids){const p=byPlacement.get(id);if(!p)throw new Error(`Placement inconnu dans la notice : ${id}`);const key=`${p.category}|${p.part_id}`,row=counts.get(key)??{partId:p.part_id,category:p.category,quantity:0};row.quantity++;counts.set(key,row);}return[...counts.values()].sort((a,b)=>a.partId.localeCompare(b.partId));}
function renderSummary(bundle){const m=bundle.brick_model;subtitle.textContent=`Bâtiment ${bundle.building_id}`;summary.innerHTML=[['Pièces',bundle.bom.total_parts],['Types',bundle.bom.unique_part_types],['Étapes',bundle.assembly_plan.total_steps],['Taille',`${m.width_studs} × ${m.depth_studs} tenons`]].map(([l,v])=>`<div><dt>${l}</dt><dd>${v}</dd></div>`).join('');}
function projectPoint(x,y,z){return{x:(x-y)*.88,y:(x+y)*.44-z*1.12};}
function shade(hex,factor){const v=parseInt(hex.slice(1),16),c=s=>Math.max(0,Math.min(255,Math.round(s*factor)));return`rgb(${c((v>>16)&255)}, ${c((v>>8)&255)}, ${c(v&255)})`;}
function cuboidPolygons(part){const{width:w,length:l,height:h}=parseDimensions(part),x0=part.x_studs,x1=x0+w,y0=part.y_studs,y1=y0+l,z0=part.z_plates*PLATE_WORLD_HEIGHT,z1=z0+h,p=projectPoint;return{top:[p(x0,y0,z1),p(x1,y0,z1),p(x1,y1,z1),p(x0,y1,z1)],right:[p(x1,y0,z0),p(x1,y1,z0),p(x1,y1,z1),p(x1,y0,z1)],left:[p(x0,y1,z0),p(x1,y1,z0),p(x1,y1,z1),p(x0,y1,z1)]};}
function slopePolygons(part){const{width:w,length:l}=parseDimensions(part),z0=part.z_plates*PLATE_WORLD_HEIGHT,high=z0+1.2,low=z0+.06,x0=part.x_studs,x1=x0+w,y0=part.y_studs,y1=y0+l,p=projectPoint,alongX=part.rotation_quarter_turns%2===0,neg=part.roof_side==='negative';let a0,a1,b0,b1;if(alongX){const zl=neg?low:high,zr=neg?high:low;a0={x:x0,y:y0,z:zl};a1={x:x0,y:y1,z:zl};b0={x:x1,y:y0,z:zr};b1={x:x1,y:y1,z:zr};}else{const zf=neg?low:high,zb=neg?high:low;a0={x:x0,y:y0,z:zf};a1={x:x1,y:y0,z:zf};b0={x:x0,y:y1,z:zb};b1={x:x1,y:y1,z:zb};}const base=[p(x0,y0,z0),p(x1,y0,z0),p(x1,y1,z0),p(x0,y1,z0)],top=[p(a0.x,a0.y,a0.z),p(b0.x,b0.y,b0.z),p(b1.x,b1.y,b1.z),p(a1.x,a1.y,a1.z)];return{top,right:[base[1],base[2],top[2],top[1]],left:[base[2],base[3],top[3],top[2]],extra:[[base[0],base[1],top[1],top[0]],[base[3],base[0],top[0],top[3]]]};}
function partProjectedPolygons(part){return part.category==='roof_tile'&&part.part_id.startsWith('BRICK_SLOPED_')?slopePolygons(part):cuboidPolygons(part);}
function pointsAttr(points,transform){return points.map(p=>{const q=transform(p);return`${q.x.toFixed(2)},${q.y.toFixed(2)}`;}).join(' ');}
function svgPolygon(points,fill,transform){return `<polygon points="${pointsAttr(points,transform)}" fill="${fill}" stroke="rgba(31,41,55,.28)" stroke-width="0.8" vector-effect="non-scaling-stroke"/>`;}
function buildStepPreview(bundle,visibleIds,currentIds){const visible=bundle.brick_model.parts.filter(p=>visibleIds.has(p.placement_id));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('step-preview');svg.setAttribute('viewBox','0 0 960 560');svg.setAttribute('role','img');svg.setAttribute('aria-label','Vue isométrique de cette étape de montage');if(!visible.length)return svg;const drawings=visible.map(part=>({part,polygons:partProjectedPolygons(part),depth:part.x_studs+part.y_studs+part.z_plates*.08})).sort((a,b)=>a.depth-b.depth);const pts=drawings.flatMap(e=>[...e.polygons.top,...e.polygons.right,...e.polygons.left,...(e.polygons.extra??[]).flat()]),minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y)),pad=54,scale=Math.min((960-pad*2)/Math.max(maxX-minX,1),(560-pad*2)/Math.max(maxY-minY,1)),ox=(960-(maxX-minX)*scale)/2-minX*scale,oy=(560-(maxY-minY)*scale)/2-minY*scale,transform=p=>({x:p.x*scale+ox,y:p.y*scale+oy});let markup='<rect width="960" height="560" rx="18" fill="#f7f9fc"/>';for(const{part,polygons}of drawings){const current=currentIds.has(part.placement_id),base=current?(CATEGORY_COLORS[part.category]??'#e5a15f'):PREVIOUS_TOP,sideA=current?shade(base,.83):PREVIOUS_SIDE_A,sideB=current?shade(base,.72):PREVIOUS_SIDE_B;for(const extra of polygons.extra??[])markup+=svgPolygon(extra,sideB,transform);markup+=svgPolygon(polygons.left,sideB,transform)+svgPolygon(polygons.right,sideA,transform)+svgPolygon(polygons.top,base,transform);}markup+=`<g font-family="system-ui, sans-serif" font-size="18" font-weight="650" fill="#344054"><rect x="28" y="22" width="18" height="18" rx="3" fill="${PREVIOUS_TOP}" stroke="#98a2b3"/><text x="56" y="37">Déjà monté</text><rect x="190" y="22" width="18" height="18" rx="3" fill="#e5a15f"/><text x="218" y="37">À ajouter</text></g>`;svg.innerHTML=markup;return svg;}
function renderSteps(bundle){const byPlacement=partMap(bundle),visibleIds=new Set();let cumulative=0;stepsEl.innerHTML='';for(const step of bundle.assembly_plan.steps){const currentIds=new Set(step.placement_ids);for(const id of currentIds)visibleIds.add(id);cumulative+=currentIds.size;const rows=aggregateStepParts(step,byPlacement).map(({partId,category,quantity})=>`<div class="part-row"><span class="part-swatch ${category}"></span><span class="part-id">${partId}</span><span class="quantity">× ${quantity}</span></div>`).join(''),card=document.createElement('article');card.className='step-card';card.innerHTML=`<div class="step-heading"><div><p class="step-kicker">Ajouter ${step.placement_ids.length} pièce(s)</p><h2>Étape ${step.sequence}</h2></div><span>${step.title}</span></div><div class="visual-slot"></div><div class="step-layout"><div><h3>Pièces à ajouter</h3><div class="part-list">${rows}</div></div><div class="step-note"><strong>${cumulative}</strong><span>/ ${bundle.assembly_plan.total_parts}</span><small>pièces montées</small></div></div>`;card.querySelector('.visual-slot').appendChild(buildStepPreview(bundle,new Set(visibleIds),currentIds));stepsEl.appendChild(card);}}
function renderBundle(bundle){validateBundle(bundle);currentBundle=bundle;renderSummary(bundle);renderSteps(bundle);message.textContent='';}
function csvText(bundle){return`${['part_id,category,quantity',...bundle.bom.lines.map(l=>`${l.part_id},${l.category},${l.quantity}`)].join('\n')}\n`;}
function downloadBom(bundle){const blob=new Blob([csvText(bundle)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${bundle.building_id}-bom.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
async function loadSample(){message.textContent='Chargement…';try{const r=await fetch('./sample-export.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);renderBundle(await r.json());}catch(e){message.textContent=e.message;}}
fileInput.addEventListener('change',async()=>{const f=fileInput.files?.[0];if(!f)return;try{renderBundle(JSON.parse(await f.text()));}catch(e){message.textContent=e.message;}finally{fileInput.value='';}});loadSampleButton.addEventListener('click',loadSample);printButton.addEventListener('click',()=>window.print());downloadBomButton.addEventListener('click',()=>{if(currentBundle)downloadBom(currentBundle);});loadSample();