const photosInput=document.querySelector('#photos'),photoList=document.querySelector('#photo-list'),notesInput=document.querySelector('#notes'),knownWidthInput=document.querySelector('#known-width'),studsInput=document.querySelector('#studs'),apiInput=document.querySelector('#api-url'),analyzeButton=document.querySelector('#analyze'),refineButton=document.querySelector('#refine'),downloadButton=document.querySelector('#download-model'),buildButton=document.querySelector('#build-bricks'),statusEl=document.querySelector('#status'),emptyState=document.querySelector('#empty-state'),resultEl=document.querySelector('#result'),resultName=document.querySelector('#result-name'),confidenceEl=document.querySelector('#confidence'),confirmationCard=document.querySelector('#confirmation-card'),questionsEl=document.querySelector('#questions'),assumptionsEl=document.querySelector('#assumptions'),jsonPreview=document.querySelector('#json-preview');
let analysis=null;
const DEFAULT_API_URL='https://brickhouse-api.onrender.com';
apiInput.value=localStorage.getItem('brickhouse.engineApiUrl')??DEFAULT_API_URL;
function apiBase(){return apiInput.value.trim().replace(/\/$/,'');}
apiInput.addEventListener('change',()=>{const base=apiBase();if(base)localStorage.setItem('brickhouse.engineApiUrl',base);else localStorage.removeItem('brickhouse.engineApiUrl');});
function selectedPhotos(){return [...(photosInput.files??[])];}
function renderPhotoList(){const files=selectedPhotos();photoList.innerHTML=files.map((file,index)=>`<div class="photo-chip" title="${file.name}">${index+1}. ${file.name}</div>`).join('');if(files.length>6)statusEl.textContent='Maximum 6 photos : retirez-en quelques-unes.';else if(files.length)statusEl.textContent=`${files.length} photo(s) prête(s) pour l’analyse.`;}
photosInput.addEventListener('change',renderPhotoList);
function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function escapeHtml(value){return String(value).replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));}
function renderAnalysis(value){analysis=value;emptyState.hidden=true;resultEl.hidden=false;resultName.textContent=value.building.name;confidenceEl.textContent=`${Math.round(value.confidence*100)} %`;confirmationCard.hidden=!value.needs_confirmation;questionsEl.innerHTML=value.questions.length?value.questions.map((q,index)=>`<div class="question ${q.importance}" data-question-id="${escapeHtml(q.id)}"><strong>${escapeHtml(q.question)}</strong><small>${escapeHtml(q.reason)}</small><label for="answer-${index}">Votre réponse</label><textarea id="answer-${index}" class="answer" rows="2" placeholder="Écrivez ce que vous savez…"></textarea></div>`).join(''):'<p>Aucune question importante pour cette proposition.</p>';refineButton.disabled=!value.questions.length;assumptionsEl.innerHTML=value.assumptions.length?value.assumptions.map(item=>`<li>${escapeHtml(item)}</li>`).join(''):'<li>Aucune hypothèse explicitée.</li>';jsonPreview.textContent=JSON.stringify(value.building,null,2);downloadButton.disabled=false;buildButton.disabled=false;}
function clarificationContext(){if(!analysis)return'';const answers=[...questionsEl.querySelectorAll('.question')].map((node,index)=>{const answer=node.querySelector('.answer')?.value.trim()??'';if(!answer)return null;const q=analysis.questions[index];return`Q: ${q.question}\nR: ${answer}`;}).filter(Boolean);if(!answers.length)return'';return`\n\nREFINEMENT REQUEST. Here is the previous BrickHouse proposal:\n${JSON.stringify(analysis.building)}\n\nUser answers to BrickHouse clarification questions:\n${answers.join('\n\n')}\nUpdate the proposal to honor these answers. Facts explicitly supplied in these answers are user_provided. Re-evaluate assumptions, confidence, needs_confirmation and remaining questions.`;}
async function runAnalysis(extraContext=''){const files=selectedPhotos(),base=apiBase();if(!files.length){statusEl.textContent='Ajoutez au moins une photo.';return;}if(files.length>6){statusEl.textContent='Maximum 6 photos.';return;}if(!base){statusEl.textContent='L’API BrickHouse doit être hébergée pour lancer l’analyse photo.';return;}const form=new FormData();for(const file of files)form.append('photos',file,file.name);const notes=[notesInput.value.trim(),extraContext].filter(Boolean).join('\n');if(notes)form.append('user_notes',notes);if(knownWidthInput.value)form.append('known_front_width_m',knownWidthInput.value);analyzeButton.disabled=true;refineButton.disabled=true;downloadButton.disabled=true;buildButton.disabled=true;statusEl.textContent=extraContext?'Mise à jour de la reconstruction avec vos réponses…':'Analyse des vues et reconstruction de la maison…';try{localStorage.setItem('brickhouse.engineApiUrl',base);const response=await fetch(`${base}/api/v1/analyze-photos`,{method:'POST',body:form});const payload=await response.json();if(!response.ok)throw new Error(typeof payload.detail==='string'?payload.detail:`Erreur HTTP ${response.status}`);renderAnalysis(payload);statusEl.textContent=payload.needs_confirmation?'Proposition mise à jour. Il reste des éléments à confirmer ou vous pouvez conserver les estimations.':'Proposition confirmée avec suffisamment de confiance pour lancer la construction.';}catch(error){statusEl.textContent=`Analyse impossible : ${error.message}`;if(analysis){downloadButton.disabled=false;buildButton.disabled=false;refineButton.disabled=!analysis.questions.length;}}finally{analyzeButton.disabled=false;}}
analyzeButton.addEventListener('click',()=>runAnalysis());
refineButton.addEventListener('click',()=>{const context=clarificationContext();if(!context){statusEl.textContent='Répondez à au moins une question avant de relancer l’analyse.';return;}runAnalysis(context);});
downloadButton.addEventListener('click',()=>{if(analysis)downloadJson(analysis.building,`${analysis.building.id}.json`);});
buildButton.addEventListener('click',async()=>{if(!analysis)return;const base=apiBase();if(!base){statusEl.textContent='URL API manquante.';return;}buildButton.disabled=true;statusEl.textContent='Conversion de la proposition en construction réelle…';try{const response=await fetch(`${base}/api/v1/build`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({building:analysis.building,front_width_studs:Number(studsInput.value)||48})});const payload=await response.json();if(!response.ok)throw new Error(typeof payload.detail==='string'?payload.detail:`Erreur moteur HTTP ${response.status}`);localStorage.setItem('brickhouse.pendingExport',JSON.stringify(payload));window.location.href='./index.html';}catch(error){statusEl.textContent=`Construction impossible : ${error.message}`;buildButton.disabled=false;}});
