const photosInput=document.querySelector('#photos'),photoList=document.querySelector('#photo-list'),notesInput=document.querySelector('#notes'),knownWidthInput=document.querySelector('#known-width'),studsInput=document.querySelector('#studs'),apiInput=document.querySelector('#api-url'),analyzeButton=document.querySelector('#analyze'),downloadButton=document.querySelector('#download-model'),buildButton=document.querySelector('#build-bricks'),statusEl=document.querySelector('#status'),emptyState=document.querySelector('#empty-state'),resultEl=document.querySelector('#result'),resultName=document.querySelector('#result-name'),confidenceEl=document.querySelector('#confidence'),confirmationCard=document.querySelector('#confirmation-card'),questionsEl=document.querySelector('#questions'),assumptionsEl=document.querySelector('#assumptions'),jsonPreview=document.querySelector('#json-preview');
let analysis=null;
apiInput.value=localStorage.getItem('brickhouse.engineApiUrl')??'';
function apiBase(){return apiInput.value.trim().replace(/\/$/,'');}
apiInput.addEventListener('change',()=>{const base=apiBase();if(base)localStorage.setItem('brickhouse.engineApiUrl',base);else localStorage.removeItem('brickhouse.engineApiUrl');});
function selectedPhotos(){return [...(photosInput.files??[])];}
function renderPhotoList(){const files=selectedPhotos();photoList.innerHTML=files.map((file,index)=>`<div class="photo-chip" title="${file.name}">${index+1}. ${file.name}</div>`).join('');if(files.length>6)statusEl.textContent='Maximum 6 photos : retirez-en quelques-unes.';else if(files.length)statusEl.textContent=`${files.length} photo(s) prête(s) pour l’analyse.`;}
photosInput.addEventListener('change',renderPhotoList);
function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function renderAnalysis(value){analysis=value;emptyState.hidden=true;resultEl.hidden=false;resultName.textContent=value.building.name;confidenceEl.textContent=`${Math.round(value.confidence*100)} %`;confirmationCard.hidden=!value.needs_confirmation;questionsEl.innerHTML=value.questions.length?value.questions.map(q=>`<div class="question ${q.importance}"><strong>${q.question}</strong><small>${q.reason}</small></div>`).join(''):'<p>Aucune question importante pour cette proposition.</p>';assumptionsEl.innerHTML=value.assumptions.length?value.assumptions.map(item=>`<li>${item}</li>`).join(''):'<li>Aucune hypothèse explicitée.</li>';jsonPreview.textContent=JSON.stringify(value.building,null,2);downloadButton.disabled=false;buildButton.disabled=false;}
analyzeButton.addEventListener('click',async()=>{const files=selectedPhotos(),base=apiBase();if(!files.length){statusEl.textContent='Ajoutez au moins une photo.';return;}if(files.length>6){statusEl.textContent='Maximum 6 photos.';return;}if(!base){statusEl.textContent='L’API BrickHouse doit être hébergée pour lancer l’analyse photo.';return;}const form=new FormData();for(const file of files)form.append('photos',file,file.name);if(notesInput.value.trim())form.append('user_notes',notesInput.value.trim());if(knownWidthInput.value)form.append('known_front_width_m',knownWidthInput.value);analyzeButton.disabled=true;downloadButton.disabled=true;buildButton.disabled=true;statusEl.textContent='Analyse des vues et reconstruction de la maison…';try{localStorage.setItem('brickhouse.engineApiUrl',base);const response=await fetch(`${base}/api/v1/analyze-photos`,{method:'POST',body:form});const payload=await response.json();if(!response.ok)throw new Error(typeof payload.detail==='string'?payload.detail:`Erreur HTTP ${response.status}`);renderAnalysis(payload);statusEl.textContent=payload.needs_confirmation?'Proposition créée. Vérifiez les questions et hypothèses avant de construire.':'Proposition créée. Vous pouvez lancer la construction en briques.';}catch(error){statusEl.textContent=`Analyse impossible : ${error.message}`;}finally{analyzeButton.disabled=false;}});
downloadButton.addEventListener('click',()=>{if(analysis)downloadJson(analysis.building,`${analysis.building.id}.json`);});
buildButton.addEventListener('click',async()=>{if(!analysis)return;const base=apiBase();if(!base){statusEl.textContent='URL API manquante.';return;}buildButton.disabled=true;statusEl.textContent='Conversion de la proposition en construction réelle…';try{const response=await fetch(`${base}/api/v1/build`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({building:analysis.building,front_width_studs:Number(studsInput.value)||48})});const payload=await response.json();if(!response.ok)throw new Error(typeof payload.detail==='string'?payload.detail:`Erreur moteur HTTP ${response.status}`);localStorage.setItem('brickhouse.pendingExport',JSON.stringify(payload));window.location.href='./index.html';}catch(error){statusEl.textContent=`Construction impossible : ${error.message}`;buildButton.disabled=false;}});
