"""Deterministic facade details that never fake window joinery with wall bricks."""
from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field
from brickhouse.building.models import BuildingModel, Facade, OpeningType
from .building_layout import BuildingBrickShell

class FacadeDetailPlacement(BaseModel):
    part_id: str
    category: Literal["facade_detail"] = "facade_detail"
    facade: Facade
    x_studs: int = Field(ge=0); y_studs: int = Field(ge=0); z_plates: int = Field(ge=0)
    rotation_quarter_turns: Literal[0,1,2,3] = 0

def _to_global(facade: Facade, local_x: int, course: int, width_studs: int, depth_studs: int)->tuple[int,int,int]:
    z=course*3
    if facade is Facade.FRONT:return local_x,0,z
    if facade is Facade.REAR:return width_studs-local_x-1,depth_studs-1,z
    if facade is Facade.RIGHT:return width_studs-1,local_x,z
    return 0,depth_studs-local_x-1,z

def generate_window_surrounds(building: BuildingModel, shell: BuildingBrickShell, *, skip_opening_ids: set[str] | None = None)->list[FacadeDetailPlacement]:
    """Add only masonry details that are truly outside the glazing void.

    Real frame+pane assemblies are generated by windows.py. Historically this
    fallback drew mullions/transoms with BRICK_1X1 cells *inside* unsupported
    windows, making them look like wall bars. That is architecturally false.
    Unsupported windows now remain clean openings until a real LEGO assembly is
    available. A requested sill may still be represented one course below the
    opening, because that cell is outside the glazing void.
    """
    skipped=skip_opening_ids or set()
    openings={opening.id:opening for opening in building.openings}
    walls={wall.facade:wall for wall in shell.walls};front=walls[Facade.FRONT].grid.width_studs;depth=walls[Facade.RIGHT].grid.width_studs
    placements=[]
    for facade in (Facade.FRONT,Facade.REAR,Facade.LEFT,Facade.RIGHT):
        wall=walls[facade]
        for raster in wall.grid.openings:
            if raster.id in skipped:continue
            opening=openings.get(raster.id)
            if not opening or opening.type is not OpeningType.WINDOW:continue
            if not opening.has_sill or raster.z_bricks<=0:continue
            sill_course=raster.z_bricks-1
            for local_x in range(raster.x_studs,raster.x_studs+raster.width_studs):
                x,y,z=_to_global(facade,local_x,sill_course,front,depth)
                placements.append(FacadeDetailPlacement(part_id="BRICK_1X1",facade=facade,x_studs=x,y_studs=y,z_plates=z))
    return placements
